# Generated by Django 2.0.9 on 2018-12-18 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CustomUsers.UserStatus', verbose_name='User Status'),
        ),
    ]
